# Generated by Django 3.1.6 on 2021-02-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='Caption',
        ),
        migrations.RemoveField(
            model_name='memes',
            name='memeImage',
        ),
        migrations.RemoveField(
            model_name='memes',
            name='memeOwner',
        ),
        migrations.AddField(
            model_name='memes',
            name='caption',
            field=models.TextField(default='none', max_length=120),
        ),
        migrations.AddField(
            model_name='memes',
            name='name',
            field=models.CharField(default='jhon', max_length=20),
        ),
        migrations.AddField(
            model_name='memes',
            name='url',
            field=models.CharField(default='this is a caption', max_length=100),
        ),
    ]
