# Generated by Django 3.1.6 on 2021-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210206_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='caption',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='memes',
            name='url',
            field=models.CharField(default='this is a caption', max_length=400),
        ),
    ]
