# Generated by Django 3.1.6 on 2021-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210211_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='name',
            field=models.CharField(default='jhon', max_length=50),
        ),
    ]
